// Import und Export der Module, die für Angular Material nötig sind

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { HttpClientModule } from '@angular/common/http';
import {CdkTableModule} from '@angular/cdk/table';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { 
         MatIconModule,
         MatGridListModule,   
         MatMenuModule,
         MatToolbarModule,
         MatFormField, 
         MatFormFieldModule,
         MatListModule,
         MatCheckbox,
         MatAutocompleteModule,
         MatButtonModule,
         MatCardModule,
         MatCheckboxModule,
         MatChipsModule,
         MatStepperModule,
         MatDatepickerModule,
         MatDialogModule,
         MatExpansionModule,
         MatNativeDateModule,
         MatPaginatorModule,
         MatProgressBarModule,
         MatProgressSpinnerModule,
         MatRadioModule,
         MatRippleModule,
         MatSelectModule,
         MatSidenavModule,
         MatSliderModule,
         MatSnackBarModule,
         MatSortModule,
         MatTableModule,
         MatTabsModule,
         MatTooltipModule,
         MatInputModule,} from '@angular/material';

@NgModule({
  imports: [ 
    MatIconModule,
         MatGridListModule,   
         MatMenuModule,
         MatToolbarModule,
         MatIconModule,
         MatFormFieldModule,
         MatListModule,
         MatInputModule,
         MatAutocompleteModule,
         MatButtonModule,
         MatCardModule,
         MatCheckboxModule,
         MatChipsModule,
         MatStepperModule,
         MatDatepickerModule,
         MatDialogModule,
         MatExpansionModule,
         MatNativeDateModule,
         MatPaginatorModule,
         MatProgressBarModule,
         MatProgressSpinnerModule,
         MatRadioModule,
         MatRippleModule,
         MatSelectModule,
         MatSidenavModule,
         MatSliderModule,
         MatSnackBarModule,
         MatSortModule,
         MatTableModule,
         MatTabsModule,
         MatTooltipModule,
         MatInputModule,],
  exports: [ 
    MatIconModule,
    MatGridListModule,   
         MatMenuModule,
         MatToolbarModule,
         MatIconModule,
         MatFormFieldModule,
         MatListModule,
         MatInputModule,
         MatAutocompleteModule,
         MatButtonModule,
         MatCardModule,
         MatCheckboxModule,
         MatChipsModule,
         MatStepperModule,
         MatDatepickerModule,
         MatDialogModule,
         MatExpansionModule,
         MatNativeDateModule,
         MatPaginatorModule,
         MatProgressBarModule,
         MatProgressSpinnerModule,
         MatRadioModule,
         MatRippleModule,
         MatSelectModule,
         MatSidenavModule,
         MatSliderModule,
         MatSnackBarModule,
         MatSortModule,
         MatTableModule,
         MatTabsModule,
         MatTooltipModule,
         MatInputModule,]
})
export class MaterialAppModule {}